name: Flutter Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Build APK
        run: |
          flutter pub get
          cd android
          # 1. GradleWrapper dosyası yoksa veya bozuksa en baştan oluştur
          gradle wrapper --gradle-version 8.4
          
          # 2. Çalıştırma yetkisi ver (Çok önemli!)
          chmod +x gradlew
          
          # 3. Derlemeyi başlat
          ./gradlew assembleRelease --no-daemon
          
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
          
